version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: "zavtratips_backend"
    image: firya/zavtratips
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - TELEGRAM_DEFAULT_ADMIN=$TELEGRAM_DEFAULT_ADMIN
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - GOOGLE_SPREADSHEET_URL=$GOOGLE_SPREADSHEET_URL
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=$GOOGLE_SERVICE_ACCOUNT_EMAIL
      - GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY
      - OMDB_API_KEY=$OMDB_API_KEY
      - RAWG_API_KEY=$RAWG_API_KEY
      - MONGO_USER=$MONGO_USERNAME
      - MONGO_PASS=$MONGO_PASSWORD
