version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "zavtratips_backend"
    image: "firya/zavtratips_backend:latest"
    volumes:
      - ./backend/src:/app/src
    restart: always
    ports:
      - "8080:3001"
    environment:
      - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST_BOT
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - TELEGRAM_DEFAULT_ADMIN=$TELEGRAM_DEFAULT_ADMIN
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - GOOGLE_SPREADSHEET_URL=$GOOGLE_SPREADSHEET_URL
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=$GOOGLE_SERVICE_ACCOUNT_EMAIL
      - GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY
      - OMDB_API_KEY=$OMDB_API_KEY
      - RAWG_API_KEY=$RAWG_API_KEY
    depends_on:
      - mongo

  mongo:
    container_name: "zavtratips_mongo"
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  default:
    name: nginx-proxy
