version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "zavtratips_backend"
    image: firya/zavtratips
    volumes:
      - ./backend/src:/app/src
    restart: always
    environment:
      - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - TELEGRAM_DEFAULT_ADMIN=$TELEGRAM_DEFAULT_ADMIN
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - GOOGLE_SPREADSHEET_URL=$GOOGLE_SPREADSHEET_URL
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=$GOOGLE_SERVICE_ACCOUNT_EMAIL
      - GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY
      - OMDB_API_KEY=$OMDB_API_KEY
      - RAWG_API_KEY=$RAWG_API_KEY
      - MONGO_USER=$MONGO_USERNAME
      - MONGO_PASS=$MONGO_PASSWORD
    depends_on:
      - mongo

  mongo:
    container_name: "zavtratips_mongo"
    image: mongo
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=server
    ports:
      - "27017:27017"

networks:
  default:
    name: nginx-proxy
