name: Publish Docker images

on:
  push:
    branches:
      - main

jobs:
  update_ssh:
    name: Telling DigitalOcean server to update
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd zavtratips
            git reset --hard origin/main
            git pull origin main
            docker compose stop
            docker compose build --no-cache
            docker compose up -d --force-recreate
